version: "2"

services:
  frontend:
    build: .
    command: /code/start_frontend.sh
    ports:
      - 8080:8080
    links:
      - postgres
      - redis
      - backend
    depends_on:
      - postgres
      - redis
      - backend
    env_file:
      - .env_docker
  backend:
    build: .
    ports:
      - 5000:5000
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    env_file:
      - .env_docker
  postgres:
    image: mdillon/postgis:11
  redis:
    image: redis:5.0.5
